import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import {
  listBacklog, getBacklogTask, updateTaskStatus, addTaskNote, listAgentRuns,
} from "./backlog-store.js";
import { runAgent } from "./agent/pipeline.js";
import { pushTasksToSlack, pullSlackToTasks, pushClosedTasksToSlack } from "./slack-sync.js";

function formatResult(data: unknown): string {
  return JSON.stringify(data, null, 2);
}

export function registerBacklogTools(server: McpServer) {
  server.tool(
    "backlog_list",
    "List SEO backlog tasks. Filters by domain, status, priority, category. Tasks are auto-generated by the agent (DeepSeek + Opus pipeline) and can be manually marked pendiente / en_progreso / ejecutada / descartada.",
    {
      domain: z.string().optional(),
      status: z.enum(["pendiente", "en_progreso", "ejecutada", "descartada"]).optional(),
      priority: z.enum(["alta", "media", "baja"]).optional(),
      category: z.enum(["technical", "on-page", "content", "social", "link-building", "ai-optimization", "schema", "sitemap"]).optional(),
      limit: z.number().int().positive().max(500).optional(),
    },
    async ({ domain, status, priority, category, limit }) => {
      const rows = await listBacklog({ domain, status, priority, category, limit });
      return { content: [{ type: "text" as const, text: formatResult({ total: rows.length, rows }) }] };
    }
  );

  server.tool(
    "backlog_get",
    "Get full detail of a backlog task by id (description, rationale, evidence, status history).",
    { id: z.number().int() },
    async ({ id }) => {
      const task = await getBacklogTask(id);
      if (!task) return { content: [{ type: "text" as const, text: formatResult({ error: "not_found", id }) }] };
      return { content: [{ type: "text" as const, text: formatResult(task) }] };
    }
  );

  server.tool(
    "backlog_update_status",
    "Change a task's status. Marking ejecutada or descartada also sets closed_at. Optionally pass notes and assignee.",
    {
      id: z.number().int(),
      status: z.enum(["pendiente", "en_progreso", "ejecutada", "descartada"]),
      notes: z.string().optional(),
      assignee: z.string().optional(),
    },
    async ({ id, status, notes, assignee }) => {
      const updated = await updateTaskStatus(id, status, notes, assignee);
      return { content: [{ type: "text" as const, text: formatResult(updated ?? { error: "not_found", id }) }] };
    }
  );

  server.tool(
    "backlog_add_note",
    "Append a note to a task (preserves history with timestamp dividers).",
    { id: z.number().int(), note: z.string() },
    async ({ id, note }) => {
      const stamped = `[${new Date().toISOString()}] ${note}`;
      const updated = await addTaskNote(id, stamped);
      return { content: [{ type: "text" as const, text: formatResult(updated ?? { error: "not_found", id }) }] };
    }
  );

  server.tool(
    "agent_run_now",
    "Manually trigger the SEO agent pipeline (DeepSeek classifies signals, Opus prioritizes tasks). Returns the run summary with proposed/inserted/updated counts and total cost.",
    {},
    async () => {
      const result = await runAgent();
      return { content: [{ type: "text" as const, text: formatResult(result) }] };
    }
  );

  server.tool(
    "backlog_slack_sync_now",
    "Trigger a manual two-way Slack sync of the backlog. Pulls completed items from Slack (mark local tasks as ejecutada) then pushes pending/in-progress local tasks to the Slack list 'Sprint de Marketing' under the 'Backlog SEO Agent' status. The cron runs this every 2 hours; this tool lets you force it.",
    {},
    async () => {
      const inbound = await pullSlackToTasks();
      const closed = await pushClosedTasksToSlack();
      const outbound = await pushTasksToSlack(50);
      return { content: [{ type: "text" as const, text: formatResult({ inbound, closed, outbound }) }] };
    }
  );

  server.tool(
    "agent_runs_list",
    "List recent agent runs with their status, task counts, cost, and any errors.",
    { limit: z.number().int().positive().max(100).optional() },
    async ({ limit }) => {
      const rows = await listAgentRuns(limit ?? 20);
      return { content: [{ type: "text" as const, text: formatResult({ runs: rows }) }] };
    }
  );
}
